import Provider from './context/AuthContext'
import './globals.css'
import ToasterContext from './context/ToasterContext'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
        <ToasterContext />
          {children}
        </Provider>
      </body>
    </html>
  )
}
